language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruit_app'

node_js:  
  - "12.22.7"

before_script:
  - psql -c 'create database  fruit_app;' -U postgres
  - psql -U postgres -d fruit_app -a -f create-tables.sql
services:
  - postgresql
