language: node.js
# language: ruby
# install:
#   - gem uninstall bundler
#   - gem install bundler --version '1.7.4'
# script: "rake"

node_js:  
  - "12.22.7"

env:
  - 'DATABASE_URL=postgresql://postgres://codex:pg123@localhost:5432/fruit_app'

before_script:
  - psql -c 'create database fruit_app' -U postgres
  - psql -U postgres -d fruit_app -a -f create-tables.sql
services:
  - postgresql
  addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4
