language: node_js

node_js:  
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruit_app'

before_script:
  - psql -c 'create database fruit_app' -U postgres
  - psql -U postgres -d fruit_app -a -f create-tables.sql
services:
  - postgresql
  addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4
